In [1]:
import requests
import json
import urllib
import time
import pandas as pd

In [2]:
dept = requests.get('https://collectionapi.metmuseum.org/public/collection/v1/departments')
dept.status_code

200

In [3]:
dept.text

'{"departments":[{"departmentId":1,"displayName":"American Decorative Arts"},{"departmentId":3,"displayName":"Ancient West Asian Art"},{"departmentId":4,"displayName":"Arms and Armor"},{"departmentId":5,"displayName":"Arts of Africa, Oceania, and the Americas"},{"departmentId":6,"displayName":"Asian Art"},{"departmentId":7,"displayName":"The Cloisters"},{"departmentId":8,"displayName":"The Costume Institute"},{"departmentId":9,"displayName":"Drawings and Prints"},{"departmentId":10,"displayName":"Egyptian Art"},{"departmentId":11,"displayName":"European Paintings"},{"departmentId":12,"displayName":"European Sculpture and Decorative Arts"},{"departmentId":13,"displayName":"Greek and Roman Art"},{"departmentId":14,"displayName":"Islamic Art"},{"departmentId":15,"displayName":"The Robert Lehman Collection"},{"departmentId":16,"displayName":"The Libraries"},{"departmentId":17,"displayName":"Medieval Art"},{"departmentId":18,"displayName":"Musical Instruments"},{"departmentId":19,"displayName":"Photographs"},{"departmentId":21,"displayName":"Modern Art"}]}\n'

In [4]:
dept.json()['departments'][0:5]

[{'departmentId': 1, 'displayName': 'American Decorative Arts'},
 {'departmentId': 3, 'displayName': 'Ancient West Asian Art'},
 {'departmentId': 4, 'displayName': 'Arms and Armor'},
 {'departmentId': 5,
  'displayName': 'Arts of Africa, Oceania, and the Americas'},
 {'departmentId': 6, 'displayName': 'Asian Art'}]

In [5]:
dept_df = pd.DataFrame(dept.json()['departments'])
dept_df.head()

   departmentId                                displayName
0             1                   American Decorative Arts
1             3                     Ancient West Asian Art
2             4                             Arms and Armor
3             5  Arts of Africa, Oceania, and the Americas
4             6                                  Asian Art

In [6]:
api_stem = 'https://collectionapi.metmuseum.org/public/collection/v1/search'
query = '?departmentId={}'.format('4', 'France')
api_stem+query

'https://collectionapi.metmuseum.org/public/collection/v1/search?departmentId=4'

In [7]:
test = requests.get(api_stem+query)
test.status_code

502

In [8]:
test.text

'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>\r\n<title>502 - Web server received an invalid response while acting as a gateway or proxy server.</title>\r\n<style type="text/css">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}\r\n-->\r\n</style>\r\n</head>\r\n<body>\r\n<div id="header"><h1>Server Error</h1></div>\r\n<div id="content">\r\n <div class="content-container"><fieldset>\r\n  <h2>502 - Web server received an invalid response while acting as a gateway or proxy server.</h2>\r\n  <h3>There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.</h3>\r\n </fieldset></div>\r\n</div>\r\n<script type="text/javascript" src="/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3&ns=2&cb=1139592552" async></script></body>\r\n</html>\r\n'

In [9]:
query='?departmentId={}&q={}'.format(4, 'helmet')
query

'?departmentId=4&q=helmet'

In [10]:
helmet_response = requests.get(api_stem+query)
helmet_response.status_code

200

In [11]:
helmet_response.json().keys()

dict_keys(['total', 'objectIDs'])

In [12]:
helmets = []
for i in helmet_response.json()['objectIDs'][0:10]:
    object_endpoint = 'https://collectionapi.metmuseum.org/public/collection/v1/objects/'
    helmets_response = requests.get(object_endpoint+str(i))
    helmets.append(helmets_response.json())
    time.sleep(.5)
    print(helmets_response.status_code)

200
200
200
200
200
200
200
200
200
200

In [13]:
helmets[0].keys()

dict_keys(['objectID', 'isHighlight', 'accessionNumber', 'accessionYear', 'isPublicDomain', 'primaryImage', 'primaryImageSmall', 'additionalImages', 'constituents', 'department', 'objectName', 'title', 'culture', 'period', 'dynasty', 'reign', 'portfolio', 'artistRole', 'artistPrefix', 'artistDisplayName', 'artistDisplayBio', 'artistSuffix', 'artistAlphaSort', 'artistNationality', 'artistBeginDate', 'artistEndDate', 'artistGender', 'artistWikidata_URL', 'artistULAN_URL', 'objectDate', 'objectBeginDate', 'objectEndDate', 'medium', 'dimensions', 'measurements', 'creditLine', 'geographyType', 'city', 'state', 'county', 'country', 'region', 'subregion', 'locale', 'locus', 'excavation', 'river', 'classification', 'rightsAndReproduction', 'linkResource', 'metadataDate', 'repository', 'objectURL', 'tags', 'objectWikidata_URL', 'isTimelineWork', 'GalleryNumber'])

In [14]:
helmets_df = pd.DataFrame(helmets)
helmets_df.head()

,objectID,isHighlight,accessionNumber,accessionYear,isPublicDomain,primaryImage,primaryImageSmall,additionalImages,constituents,department,...,classification,rightsAndReproduction,linkResource,metadataDate,repository,objectURL,tags,objectWikidata_URL,isTimelineWork,GalleryNumber
0,23026,True,28.60.2,1928,True,https://images.metmuseum.org/CRDImages/aa/orig...,https://images.metmuseum.org/CRDImages/aa/web-...,[https://images.metmuseum.org/CRDImages/aa/ori...,None,Arms and Armor,...,Helmets,,,2025-12-20T04:50:39.43Z,"Metropolitan Museum of Art, New York, NY",https://www.metmuseum.org/art/collection/searc...,None,https://www.wikidata.org/wiki/Q29383131,True,377
1,27936,True,04.3.456a,1904,True,https://images.metmuseum.org/CRDImages/aa/orig...,https://images.metmuseum.org/CRDImages/aa/web-...,[https://images.metmuseum.org/CRDImages/aa/ori...,None,Arms and Armor,...,Helmets,,,2025-12-20T04:50:39.43Z,"Metropolitan Museum of Art, New York, NY",https://www.metmuseum.org/art/collection/searc...,None,https://www.wikidata.org/wiki/Q29383225,False,379
2,24028,False,36.25.126,1936,True,https://images.metmuseum.org/CRDImages/aa/orig...,https://images.metmuseum.org/CRDImages/aa/web-...,[https://images.metmuseum.org/CRDImages/aa/ori...,None,Arms and Armor,...,Helmets,,,2025-03-06T04:54:30Z,"Metropolitan Museum of Art, New York, NY",https://www.metmuseum.org/art/collection/searc...,None,https://www.wikidata.org/wiki/Q116321834,False,379
3,24667,False,38.128.1,1938,True,https://images.metmuseum.org/CRDImages/aa/orig...,https://images.metmuseum.org/CRDImages/aa/web-...,[https://images.metmuseum.org/CRDImages/aa/ori...,None,Arms and Armor,...,Helmets,,,2025-12-20T04:50:39.43Z,"Metropolitan Museum of Art, New York, NY",https://www.metmuseum.org/art/collection/searc...,None,https://www.wikidata.org/wiki/Q116326597,False,371
4,25379,False,04.3.213,1904,True,https://images.metmuseum.org/CRDImages/aa/orig...,https://images.metmuseum.org/CRDImages/aa/web-...,[https://images.metmuseum.org/CRDImages/aa/ori...,None,Arms and Armor,...,Helmets,,,2025-12-20T04:50:39.43Z,"Metropolitan Museum of Art, New York, NY",https://www.metmuseum.org/art/collection/searc...,None,https://www.wikidata.org/wiki/Q116321567,False,379

In [15]:
helmets_df.iloc[0]['primaryImage']

'https://images.metmuseum.org/CRDImages/aa/original/DP-18127-002.jpg'

In [16]:
urllib.parse.quote('Arms and Armor'), urllib.parse.quote_plus('Arms and Armor')

('Arms%20and%20Armor', 'Arms+and+Armor')

For an example of authentication, see https://artsearch.io/docs/random-artwork-api/

In [17]:
key = pd.read_csv(r'D:\Syncthing-Red\Dropbox-Backup\artsearch_key.csv')
# key['key'].iloc[0]
header = {'x-api-key': key['key'].iloc[0]}
# header

In [18]:
random_art_response = requests.get('https://api.artsearch.io/artworks/random', headers = header)
random_art_response.status_code

200

In [19]:
random_art_response.json()

{'id': 26375054,
 'title': 'Duitse Reichsarbeitsdienst opgesteld op het Museumplein',
 'image': 'https://img.artsearch.io/artworks/duitse_reichsarbeitsdienst_opgesteld_op_het_museumplein_unknown243_1940.jpg',
 'start_date': 1940,
 'end_date': 1940,
 'art_types': ['photograph'],
 'description': 'The photograph titled "Duitse Reichsarbeitsdienst opgesteld op het Museumplein," created in 1940, depicts a formation of young men from the German Reich Labor Service (Reichsarbeitsdienst) standing in rigid alignment at the Museumplein, a notable square in Amsterdam. Clad in uniforms typical of the era, the men are holding tools (shovels) upright, which reflects the labor-centric ideology of the organization aimed at preparing the youth for work that supported the regime’s agricultural and infrastructural goals. \n\nThe image captures a moment of military-like discipline, with the soldiers\' expressions conveying seriousness and resolve. The backdrop features architectural elements of the museum square, adding a historical context to the setting. This photograph serves not only as a documentation of a specific event but also as a visual representation of the socio-political climate of Nazi Germany at the time, illustrating the integration of labor service into the militaristic and propaganda efforts of the regime. The use of monochrome further emphasizes the starkness of the moment, enhancing its historical significance as a record of a period characterized by oppression and ideology.'}