In [1]:
import pandas as pd
import plotly.express as px
import dash
import plotly.graph_objects as go
from dash import Dash, html, dcc, Output, Input, callback

In [2]:
mb = pd.read_csv('mobile-use.csv')
mb.columns

Index(['Age', 'spBrand', 'spAge', 'spWBUseFreq', 'spSEUseFreq',
       'spComfInstallBrowser', 'spComfDefaultBrowserChange',
       'spComfDefaultSearchChange', 'Sex', 'GUID',
       'spComfInstallBrowser_recode', 'spComfDefaultBrowserChange_recode',
       'spComfDefaultSearchChange_recode', 'Ethnicity', 'Education', 'Income',
       'spComfort'],
      dtype='object')

In [3]:
app1 = Dash()
app1.layout = html.Div([
    html.H1("David's Awesome App"),
    html.H2("Some subheading"),
    dcc.Graph(id = 'spComfort-spAge_figure'),
    dcc.Slider(id = 'Age_slider')
])




if __name__ == '__main__':
    app1.run(debug = True)

In [4]:
(mb['Age'].min(), mb['Age'].max())

(18, 94)

In [5]:
app2 = Dash()
app2.layout = html.Div([
    html.H1("David's Awesome App"),
    html.H2("Some subheading"),
    dcc.Graph(id = 'spComfort-spAge_figure'),
    dcc.Slider(mb['Age'].min(),
               mb['Age'].max(),
               step = 1,
               value = mb['Age'].min(),
               id = 'Age_slider')
])

@callback(
    Output('spComfort-spAge_figure', 'figure'),
    Input('Age_slider', 'value')
)
def update_fig(age_select):
    fig = px.scatter(mb, x = 'spAge', y = 'spComfort', color = 'Sex')
    return fig

if __name__ == '__main__':
    app2.run(debug = True)

In [6]:
mb[mb['Age'] == 19]

,Age,spBrand,spAge,spWBUseFreq,spSEUseFreq,spComfInstallBrowser,spComfDefaultBrowserChange,spComfDefaultSearchChange,Sex,GUID,spComfInstallBrowser_recode,spComfDefaultBrowserChange_recode,spComfDefaultSearchChange_recode,Ethnicity,Education,Income,spComfort
84,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11c83dfa-828c-1473-0c78-0ae3a84e6613,NaN,NaN,NaN,Black or African American,High School/Tertiary/Tech. College,NaN,NaN
118,19,1.0,4.0,1.0,1.0,5.0,4.0,4.0,1,18d8abc4-98b9-9312-0046-9cf342497c23,4.0,3.0,3.0,NaN,University/Higher Education,NaN,3.333333
128,19,NaN,NaN,NaN,NaN,3.0,3.0,2.0,1,1c40ecd7-9261-daa6-8455-db6b1d839630,2.0,2.0,1.0,Black or African American,High School/Tertiary/Tech. College,NaN,1.666667
241,19,7.0,6.0,4.0,3.0,3.0,2.0,3.0,1,3517dc0b-5fe1-fd1e-cf89-eb3c9032bbe2,2.0,1.0,2.0,I prefer not to answer,University/Higher Education,NaN,1.666667
284,19,16.0,2.0,7.0,7.0,4.0,4.0,4.0,1,407dcbb7-b094-bbbd-a335-fc564014525e,3.0,3.0,3.0,Black or African American,High School/Tertiary/Tech. College,"$0 - $14,999",3.000000
367,19,1.0,3.0,1.0,1.0,5.0,2.0,3.0,1,519150f0-621a-5dde-4972-67ba09179a1b,4.0,1.0,2.0,White,University/Higher Education,NaN,2.333333
606,19,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1,83397093-4835-53ec-e111-471208688c74,0.0,0.0,0.0,White,High School/Tertiary/Tech. College,NaN,0.000000
608,19,13.0,3.0,1.0,1.0,5.0,5.0,5.0,1,83ba3497-63e5-31b8-6215-0391e0836679,4.0,4.0,4.0,White,High School/Tertiary/Tech. College,NaN,4.000000
618,19,4.0,1.0,4.0,6.0,3.0,4.0,4.0,1,85920637-efb4-2a89-56b5-31b94f7937d0,2.0,3.0,3.0,I prefer not to answer,High School/Tertiary/Tech. College,NaN,2.666667
632,19,1.0,1.0,4.0,5.0,5.0,5.0,5.0,1,878627a2-3311-1054-4220-10ad9f25fb4a,4.0,4.0,4.0,White,High School/Tertiary/Tech. College,NaN,4.000000
634,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,87edc14c-f35b-1447-29ce-f6c6f07e74ab,NaN,NaN,NaN,American Indian or Alaska Native,High School/Tertiary/Tech. College,NaN,NaN
640,19,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1,88fe6b88-0288-3e3e-760a-5cd55ade1161,0.0,0.0,0.0,White,University/Higher Education,"$50,000 - $79,999",0.000000
646,19,16.0,1.0,1.0,1.0,5.0,5.0,5.0,2,897ab929-e55c-8bb5-beab-8e51a17260c1,4.0,4.0,4.0,Black or African American,High School/Tertiary/Tech. College,NaN,4.000000
657,19,1.0,1.0,1.0,1.0,5.0,5.0,5.0,1,8c4a0f57-0bbf-22fd-8ed5-38617471ebb0,4.0,4.0,4.0,White,High School/Tertiary/Tech. College,NaN,4.000000
761,19,3.0,2.0,4.0,4.0,2.0,3.0,3.0,2,a27d2b88-f923-7ffb-a40a-1c563deb1a78,1.0,2.0,2.0,White,High School/Tertiary/Tech. College,NaN,1.666667
855,19,NaN,NaN,NaN,NaN,5.0,5.0,5.0,1,b583a652-e591-ff26-0bd0-91a8a34af5bd,4.0,4.0,4.0,White,High School/Tertiary/Tech. College,NaN,4.000000
858,19,11.0,3.0,1.0,1.0,4.0,5.0,5.0,2,b5df9a81-8a9e-2be5-0003-adf45df3897a,3.0,4.0,4.0,Black or African American,University/Higher Education,"$50,000 - $79,999",3.666667
868,19,7.0,2.0,2.0,3.0,1.0,2.0,1.0,1,b781c350-f650-ec98-45d2-f4aaf59d32a1,0.0,1.0,0.0,Black or African American,High School/Tertiary/Tech. College,NaN,0.333333
882,19,NaN,NaN,NaN,NaN,2.0,5.0,3.0,1,bae84cad-e315-6169-2c2f-7bc3fc5b0741,1.0,4.0,2.0,Black or African American,High School/Tertiary/Tech. College,NaN,2.333333
941,19,8.0,2.0,6.0,4.0,2.0,2.0,2.0,1,c4e75a5b-9695-7793-23d9-6dcc96fa57bc,1.0,1.0,1.0,White,High School/Tertiary/Tech. College,NaN,1.000000
971,19,1.0,4.0,1.0,1.0,5.0,3.0,4.0,1,ca8119c8-4d30-6aef-5f4a-2eaaa9dcaf25,4.0,2.0,3.0,White,High School/Tertiary/Tech. College,"$0 - $14,999",3.000000
991,19,4.0,1.0,1.0,1.0,3.0,3.0,3.0,2,ce3382e5-a42c-b212-f767-b518cd0d210d,2.0,2.0,2.0,White,High School/Tertiary/Tech. College,NaN,2.000000
1021,19,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2,d374bf1e-c28d-972d-ac9c-885f8c4d02f3,1.0,1.0,1.0,Black or African American,High School/Tertiary/Tech. College,"$80,000 - $99,999",1.000000
1058,19,17.0,1.0,6.0,4.0,1.0,3.0,3.0,2,dccd9abd-0358-1e1c-143f-ade671dde155,0.0,2.0,2.0,White,Secondary School,NaN,1.333333
1211,19,11.0,2.0,1.0,1.0,5.0,5.0,5.0,1,fe45197d-1bce-37ab-81ff-2e6eca841c95,4.0,4.0,4.0,White,High School/Tertiary/Tech. College,NaN,4.000000

In [7]:
app3 = Dash()
app3.layout = html.Div([
    html.H1("David's Awesome App"),
    html.H2("Some subheading"),
    dcc.Graph(id = 'spComfort-spAge_figure'),
    dcc.Slider(mb['Age'].min(),
               mb['Age'].max(),
               step = 1,
               value = mb['Age'].min(),
               id = 'Age_slider')
])

@callback(
    Output('spComfort-spAge_figure', 'figure'),
    Input('Age_slider', 'value')
)
def update_fig(age_select):
    filtered_mb = mb[mb['Age'] == age_select]
    fig = px.scatter(filtered_mb, x = 'spAge', y = 'spComfort', color = 'Sex')
    return fig

if __name__ == '__main__':
    app3.run(debug = True)

In [8]:
mb['Sex_c'] = mb['Sex'].astype('category')

In [9]:
mb[(mb['Age'] < 30 + 10) & (mb['Age'] >= 30)]

,Age,spBrand,spAge,spWBUseFreq,spSEUseFreq,spComfInstallBrowser,spComfDefaultBrowserChange,spComfDefaultSearchChange,Sex,GUID,spComfInstallBrowser_recode,spComfDefaultBrowserChange_recode,spComfDefaultSearchChange_recode,Ethnicity,Education,Income,spComfort,Sex_c
0,38,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1,0007a34a-df0f-ff99-dfc8-942cbfd6dba1,0.0,0.0,0.0,Black or African American,Secondary School,NaN,0.000000,1
5,35,16.0,2.0,1.0,1.0,5.0,5.0,5.0,2,0200deec-5baa-4e7b-c46e-e92bb9075e05,4.0,4.0,4.0,White,High School/Tertiary/Tech. College,"$50,000 - $79,999",4.000000,2
14,30,1.0,2.0,1.0,1.0,5.0,5.0,5.0,2,035d5f63-b1c2-082f-d5e1-6876fb63a584,4.0,4.0,4.0,White,High School/Tertiary/Tech. College,"$25,000 - $49,999",4.000000,2
16,33,NaN,NaN,NaN,NaN,2.0,5.0,3.0,2,03e7c0bd-a67e-f14e-233f-f7cc7cbf465a,1.0,4.0,2.0,Black or African American,High School/Tertiary/Tech. College,NaN,2.333333,2
27,36,1.0,2.0,1.0,2.0,3.0,3.0,3.0,2,05d9ca49-5638-baf7-ddc8-fdf2c7b172a4,2.0,2.0,2.0,American Indian or Alaska Native,Primary School,"$15,000 - $24,999",2.000000,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1196,39,1.0,2.0,1.0,1.0,5.0,4.0,5.0,1,fa118b29-20b8-6961-c9ab-bc3a20a6e4c3,4.0,3.0,4.0,Black or African American,Postgraduate Education,NaN,3.666667,1
1202,30,16.0,2.0,1.0,1.0,5.0,5.0,5.0,2,fbd18339-3b36-9a79-15bb-b4fa3b2ddcd1,4.0,4.0,4.0,White,University/Higher Education,"$80,000 - $99,999",4.000000,2
1207,39,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,fcf3dc83-807e-d40c-3701-ebd86f7f4541,3.0,3.0,3.0,White,Postgraduate Education,NaN,3.000000,1
1214,37,NaN,NaN,NaN,NaN,5.0,3.0,3.0,1,fe80056a-885d-9a08-0ee8-32ab50bed186,4.0,2.0,2.0,NaN,Postgraduate Education,"$50,000 - $79,999",2.666667,1
1216,31,4.0,5.0,3.0,4.0,5.0,4.0,4.0,1,fea6a10d-7174-3ffb-288f-968d8aee22ea,4.0,3.0,3.0,White,University/Higher Education,NaN,3.333333,1

In [10]:
app4 = Dash()
app4.layout = html.Div([
    html.H1("David's Awesome App"),
    html.H2("Some subheading"),
    dcc.Graph(id = 'spComfort-spAge_figure'),
    dcc.Slider(20,
               90,
               step = 10,
               value = 50,
               id = 'Age_slider')
])

@callback(
    Output('spComfort-spAge_figure', 'figure'),
    Input('Age_slider', 'value')
)
def update_fig(age_select):
    filtered_mb = mb[(mb['Age'] < age_select + 10) & (mb['Age'] >= age_select)]
    fig = px.scatter(filtered_mb, x = 'spAge', y = 'spComfort', color = 'Sex_c',
                    title = 'SP Comfort by SP Age for people {}-{} years old'.format(age_select, age_select+10))
    # f'SP Comfort by SP Age for people {age_select}-{age_select+10} years old'
    return fig

if __name__ == '__main__':
    app4.run(debug = True)

In [11]:
mb['Ethnicity'].unique()

array(['Black or African American', 'White', 'Asian',
       'American Indian or Alaska Native', nan, 'I prefer not to answer',
       'Hispanic or Latino', 'Other',
       'Native Hawaiian or Pacific Islander'], dtype=object)

In [12]:
mb[(mb['Age'] < 20 + 10) & (mb['Age'] >= 20) & (mb['Ethnicity'] == 'Black or African American')]

,Age,spBrand,spAge,spWBUseFreq,spSEUseFreq,spComfInstallBrowser,spComfDefaultBrowserChange,spComfDefaultSearchChange,Sex,GUID,spComfInstallBrowser_recode,spComfDefaultBrowserChange_recode,spComfDefaultSearchChange_recode,Ethnicity,Education,Income,spComfort,Sex_c
127,25,1.0,3.0,1.0,1.0,4.0,4.0,4.0,1,1be2beca-9d02-9f70-2648-89c9efd0592d,3.0,3.0,3.0,Black or African American,University/Higher Education,"$50,000 - $79,999",3.000000,1
132,21,5.0,1.0,1.0,1.0,5.0,4.0,4.0,2,1cd3d002-e138-fa13-1780-e7f8856e26ef,4.0,3.0,3.0,Black or African American,High School/Tertiary/Tech. College,NaN,3.333333,2
211,22,4.0,2.0,1.0,1.0,2.0,4.0,2.0,1,2e96a9b0-beb7-3cf5-1832-9ebdfbd22457,1.0,3.0,1.0,Black or African American,High School/Tertiary/Tech. College,"$25,000 - $49,999",1.666667,1
224,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,315b3bfa-0539-1ef6-9f78-0c704fdc0102,NaN,NaN,NaN,Black or African American,High School/Tertiary/Tech. College,NaN,NaN,1
231,25,2.0,3.0,5.0,3.0,1.0,1.0,1.0,2,3369dff8-9a6b-e33f-b17a-e84280526310,0.0,0.0,0.0,Black or African American,University/Higher Education,"$0 - $14,999",0.000000,2
258,22,7.0,2.0,6.0,5.0,2.0,5.0,4.0,2,3a6f40b9-c60c-de7e-e13b-774479965d51,1.0,4.0,3.0,Black or African American,High School/Tertiary/Tech. College,NaN,2.666667,2
314,21,16.0,3.0,1.0,1.0,5.0,5.0,4.0,1,452bd022-efbb-f8fe-9ca0-e7002be8b6ca,4.0,4.0,3.0,Black or African American,University/Higher Education,"$15,000 - $24,999",3.666667,1
339,29,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2,4b7860a5-031c-738d-a027-57531b33cb42,1.0,0.0,0.0,Black or African American,High School/Tertiary/Tech. College,NaN,0.333333,2
341,24,15.0,5.0,6.0,5.0,1.0,3.0,3.0,2,4bf50b48-ea56-8d7c-2fca-3cde1da76da1,0.0,2.0,2.0,Black or African American,University/Higher Education,NaN,1.333333,2
365,24,15.0,2.0,3.0,3.0,2.0,1.0,2.0,2,51176493-5d6b-6f94-ce11-533c5262b674,1.0,0.0,1.0,Black or African American,University/Higher Education,NaN,0.666667,2
382,22,4.0,1.0,6.0,6.0,3.0,3.0,3.0,1,5433896a-1b21-d63d-bbe8-be188fe28f8d,2.0,2.0,2.0,Black or African American,High School/Tertiary/Tech. College,NaN,2.000000,1
399,23,NaN,NaN,NaN,NaN,5.0,5.0,5.0,2,5903bc3b-72fd-9724-c7b9-8b287299b2d1,4.0,4.0,4.0,Black or African American,High School/Tertiary/Tech. College,NaN,4.000000,2
414,29,7.0,1.0,1.0,6.0,3.0,3.0,3.0,2,5ba05116-48fe-83e9-f097-668bd8bf3bf1,2.0,2.0,2.0,Black or African American,University/Higher Education,"$200,000 or more",2.000000,2
482,22,1.0,1.0,1.0,1.0,3.0,3.0,4.0,1,6a4c00d8-db6d-9f97-c25a-3767b1f4881b,2.0,2.0,3.0,Black or African American,University/Higher Education,NaN,2.333333,1
501,26,1.0,3.0,1.0,3.0,1.0,1.0,2.0,1,6f84b349-585e-41be-40cb-84af74b35fbc,0.0,0.0,1.0,Black or African American,High School/Tertiary/Tech. College,NaN,0.333333,1
511,24,NaN,NaN,NaN,NaN,5.0,5.0,5.0,2,7191226b-b326-88a1-4ee9-15ba27414e82,4.0,4.0,4.0,Black or African American,High School/Tertiary/Tech. College,"$25,000 - $49,999",4.000000,2
548,21,4.0,3.0,2.0,2.0,4.0,3.0,4.0,2,793435c2-6994-6927-bc40-021f0c443d2a,3.0,2.0,3.0,Black or African American,High School/Tertiary/Tech. College,"$80,000 - $99,999",2.666667,2
573,21,14.0,1.0,1.0,1.0,1.0,1.0,2.0,2,7cffb025-88ef-0653-23a7-87d47c2a75e2,0.0,0.0,1.0,Black or African American,High School/Tertiary/Tech. College,NaN,0.333333,2
592,22,1.0,4.0,NaN,NaN,5.0,5.0,5.0,2,80e8ba25-e277-e8d6-60a7-8dc39f39b9cd,4.0,4.0,4.0,Black or African American,High School/Tertiary/Tech. College,"$25,000 - $49,999",4.000000,2
615,21,NaN,NaN,NaN,NaN,1.0,1.0,3.0,2,8500037d-6119-18ac-c4ff-342bd8fe819a,0.0,0.0,2.0,Black or African American,University/Higher Education,"$15,000 - $24,999",0.666667,2
658,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,8cb3ac02-c800-857c-7780-9b980ed50cd2,NaN,NaN,NaN,Black or African American,High School/Tertiary/Tech. College,NaN,NaN,1
675,26,NaN,NaN,NaN,NaN,3.0,2.0,5.0,2,8f1b17d1-9dfd-1e7c-df53-203072cf7a3d,2.0,1.0,4.0,Black or African American,Postgraduate Education,NaN,2.333333,2
695,24,7.0,3.0,7.0,5.0,4.0,3.0,1.0,2,93425607-8695-b93f-8685-6169e7b861ef,3.0,2.0,0.0,Black or African American,Postgraduate Education,NaN,1.666667,2
739,21,6.0,1.0,4.0,2.0,2.0,4.0,2.0,2,9e0bf584-7273-d102-cf06-c2208c96b263,1.0,3.0,1.0,Black or African American,Postgraduate Education,NaN,1.666667,2
756,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,a1aa389d-7c62-a64b-241f-0f81fb813170,NaN,NaN,NaN,Black or African American,Secondary School,NaN,NaN,2
790,21,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2,a8656603-fab2-5650-a181-514e57fe7feb,0.0,0.0,0.0,Black or African American,High School/Tertiary/Tech. College,NaN,0.000000,2
822,26,NaN,NaN,NaN,NaN,3.0,3.0,5.0,1,af540220-48ef-3721-90a2-357f26c8cfc9,2.0,2.0,4.0,Black or African American,Secondary School,NaN,2.666667,1
836,25,1.0,2.0,1.0,1.0,1.0,1.0,5.0,2,b1b50a48-22c9-25bf-71ca-3d9e32a5a7a1,0.0,0.0,4.0,Black or African American,High School/Tertiary/Tech. College,NaN,1.333333,2
886,24,12.0,2.0,4.0,5.0,5.0,4.0,4.0,2,bbb31c21-da69-2160-6aa3-2b986a563fcb,4.0,3.0,3.0,Black or African American,University/Higher Education,"$0 - $14,999",3.333333,2
910,28,16.0,2.0,1.0,1.0,5.0,5.0,5.0,2,bf849ba4-e496-be5a-5c26-acafb3400049,4.0,4.0,4.0,Black or African American,High School/Tertiary/Tech. College,"$0 - $14,999",4.000000,2
928,29,7.0,1.0,1.0,2.0,4.0,3.0,3.0,1,c27bc1cf-fa8b-bb02-7c4e-f650f32cd928,3.0,2.0,2.0,Black or African American,High School/Tertiary/Tech. College,"$15,000 - $24,999",2.333333,1
953,22,NaN,NaN,NaN,NaN,1.0,3.0,5.0,1,c7a8b697-2c14-8191-6c15-8183c520cb7d,0.0,2.0,4.0,Black or African American,University/Higher Education,NaN,2.000000,1
981,25,1.0,5.0,1.0,1.0,5.0,5.0,5.0,1,cc4aa73e-5123-73bf-1abf-90614d7220d6,4.0,4.0,4.0,Black or African American,High School/Tertiary/Tech. College,"$0 - $14,999",4.000000,1
1002,25,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1,d0f436c7-f79a-6960-7c45-01df3b425f07,0.0,0.0,0.0,Black or African American,Secondary School,NaN,0.000000,1
1018,22,NaN,NaN,NaN,NaN,1.0,2.0,5.0,2,d2fe4205-9ebb-1122-2687-75d5b9d665e2,0.0,1.0,4.0,Black or African American,None completed,NaN,1.666667,2
1042,25,11.0,3.0,1.0,1.0,2.0,2.0,2.0,1,d8e7578b-cca5-c97a-6909-60cc6936576c,1.0,1.0,1.0,Black or African American,High School/Tertiary/Tech. College,NaN,1.000000,1
1135,26,NaN,NaN,NaN,NaN,5.0,NaN,4.0,2,ea671006-b78a-e589-a384-274c598cb0e1,4.0,NaN,3.0,Black or African American,University/Higher Education,"$25,000 - $49,999",NaN,2
1136,26,2.0,1.0,7.0,6.0,NaN,1.0,1.0,1,eab5cc43-c2c6-fd90-6dc1-fb9e952f0282,NaN,0.0,0.0,Black or African American,University/Higher Education,NaN,NaN,1
1170,25,1.0,6.0,2.0,2.0,3.0,3.0,3.0,1,f25b523e-8e7a-6126-9fbc-6570965586f0,2.0,2.0,2.0,Black or African American,High School/Tertiary/Tech. College,NaN,2.000000,1
1174,26,NaN,NaN,NaN,NaN,3.0,2.0,1.0,2,f3e5e69e-0204-cb82-201c-d1cedd2ae477,2.0,1.0,0.0,Black or African American,High School/Tertiary/Tech. College,NaN,1.000000,2
1187,21,1.0,1.0,5.0,5.0,1.0,2.0,1.0,2,f86b3adc-66f6-e880-b45e-0d400838863b,0.0,1.0,0.0,Black or African American,Postgraduate Education,NaN,0.333333,2

In [15]:
app5 = Dash()
app5.layout = html.Div([
    html.H1("David's Awesome App"),
    html.H2("Some subheading"),
    dcc.Graph(id = 'spComfort-spAge_figure'),
    dcc.RangeSlider(20,
               90,
               step = 10,
               value = [20, 90],
               id = 'Age_slider'),
    dcc.RadioItems(mb['Ethnicity'].unique(),
                   value = 'Black or African American',
                  id = 'Ethnicity_radio')
])

@callback(
    Output('spComfort-spAge_figure', 'figure'),
    Input('Age_slider', 'value'),
    Input('Ethnicity_radio', 'value')
)
def update_fig(age_select, ethnicity_select):
    filtered_mb = mb[(mb['Age'] < age_select[1]) & (mb['Age'] >= age_select[0]) & (mb['Ethnicity'] == ethnicity_select)]
    filtered_men = filtered_mb[filtered_mb['Sex_c'] == 1]
    filtered_women = filtered_mb[filtered_mb['Sex_c'] == 2]
    trace_men = go.Scatter(x = filtered_men['spAge'], y = filtered_men['spComfort'], mode = 'markers', name = 'Men', opacity = 0.6, marker = {'symbol': 'square'})
    trace_women = go.Scatter(x = filtered_women['spAge'], y = filtered_women['spComfort'], mode = 'markers', name = 'Women', opacity = 0.6, marker = {'symbol': 'diamond'})
    fig = go.Figure(data = [trace_men, trace_women])
    fig.update_layout(title_text = 'SP Comfort by SP Age for people {}-{} years old'.format(age_select[0], age_select[1]))
    return fig

if __name__ == '__main__':
    app5.run(debug = True)

In [14]:
app6 = Dash()

app6.layout = html.Div([
    html.Div([
        html.H1('Name'),
        html.H2('Title'),
        dcc.Graph(),
        dcc.Slider()], style = {'width': '80%'}),
    html.Div([
        dcc.Graph()])
], style = {'display': 'flex'})


if __name__ == '__main__':
    app6.run(debug = True)