In [1]:
import pandas as pd
import plotly.express as px
import dash
import plotly.graph_objects as go
from dash import Dash, html, dcc, Output, Input, callback

In [2]:
mb = pd.read_csv('mobile-use.csv')
mb.head()

,Age,spBrand,spAge,spWBUseFreq,spSEUseFreq,spComfInstallBrowser,spComfDefaultBrowserChange,spComfDefaultSearchChange,Sex,GUID,spComfInstallBrowser_recode,spComfDefaultBrowserChange_recode,spComfDefaultSearchChange_recode,Ethnicity,Education,Income,spComfort
0,38,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1,0007a34a-df0f-ff99-dfc8-942cbfd6dba1,0.0,0.0,0.0,Black or African American,Secondary School,NaN,0.000000
1,46,NaN,NaN,NaN,NaN,5.0,5.0,5.0,1,00282bac-006c-7aaf-a02e-1c038f3f9441,4.0,4.0,4.0,White,None completed,"$0 - $14,999",4.000000
2,29,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,00a4c861-1c1d-e660-60e3-ff8f0d54db96,3.0,3.0,3.0,White,University/Higher Education,"$15,000 - $24,999",3.000000
3,62,4.0,2.0,3.0,4.0,3.0,2.0,5.0,1,014ab9a2-1f31-8d9c-8e20-8e614dd9174f,2.0,1.0,4.0,Asian,High School/Tertiary/Tech. College,NaN,2.333333
4,48,22.0,7.0,5.0,5.0,4.0,4.0,4.0,1,01cf5015-1cc1-5cc2-0b97-67e45a2e18f2,3.0,3.0,3.0,White,University/Higher Education,NaN,3.000000

In [13]:
mb[(mb['Age'] > 20) & (mb['Age'] <= 40)]

,Age,spBrand,spAge,spWBUseFreq,spSEUseFreq,spComfInstallBrowser,spComfDefaultBrowserChange,spComfDefaultSearchChange,Sex,GUID,spComfInstallBrowser_recode,spComfDefaultBrowserChange_recode,spComfDefaultSearchChange_recode,Ethnicity,Education,Income,spComfort
0,38,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1,0007a34a-df0f-ff99-dfc8-942cbfd6dba1,0.0,0.0,0.0,Black or African American,Secondary School,NaN,0.000000
2,29,NaN,NaN,NaN,NaN,4.0,4.0,4.0,1,00a4c861-1c1d-e660-60e3-ff8f0d54db96,3.0,3.0,3.0,White,University/Higher Education,"$15,000 - $24,999",3.000000
5,35,16.0,2.0,1.0,1.0,5.0,5.0,5.0,2,0200deec-5baa-4e7b-c46e-e92bb9075e05,4.0,4.0,4.0,White,High School/Tertiary/Tech. College,"$50,000 - $79,999",4.000000
8,25,NaN,NaN,NaN,NaN,2.0,4.0,4.0,1,029af010-e0ce-6fc5-9c91-c7b1575265fd,1.0,3.0,3.0,White,University/Higher Education,"$50,000 - $79,999",2.333333
14,30,1.0,2.0,1.0,1.0,5.0,5.0,5.0,2,035d5f63-b1c2-082f-d5e1-6876fb63a584,4.0,4.0,4.0,White,High School/Tertiary/Tech. College,"$25,000 - $49,999",4.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1209,25,4.0,2.0,1.0,1.0,1.0,2.0,2.0,2,fde3cd21-ea6d-3dbe-27a3-fac81e000bc8,0.0,1.0,1.0,White,High School/Tertiary/Tech. College,"$15,000 - $24,999",0.666667
1214,37,NaN,NaN,NaN,NaN,5.0,3.0,3.0,1,fe80056a-885d-9a08-0ee8-32ab50bed186,4.0,2.0,2.0,NaN,Postgraduate Education,"$50,000 - $79,999",2.666667
1216,31,4.0,5.0,3.0,4.0,5.0,4.0,4.0,1,fea6a10d-7174-3ffb-288f-968d8aee22ea,4.0,3.0,3.0,White,University/Higher Education,NaN,3.333333
1220,23,NaN,NaN,NaN,NaN,2.0,1.0,3.0,1,ffb53405-8ed0-228e-6d87-039e68c347e2,1.0,0.0,2.0,Hispanic or Latino,High School/Tertiary/Tech. College,Prefer not to say,1.000000
1221,22,1.0,3.0,1.0,1.0,5.0,4.0,1.0,2,ffbced15-bdb1-c1d1-6097-da978bf945f8,4.0,3.0,0.0,White,High School/Tertiary/Tech. College,"$25,000 - $49,999",2.333333

In [ ]:
app1 = Dash()
app1.layout = html.Div([
    html.H1("David's Awesome App"),
    html.H2("Some subheading"),
    dcc.Graph(id = 'spComfort-spAge_figure'),
    dcc.RangeSlider(20,
               90,
               step = 10,
               value = [20, 90],
               id = 'Age_slider')
])

@callback(
    Output('spComfort-spAge_figure', 'figure'),
    Input('Age_slider', 'value')
)
def update_fig(age_select):
    filtered_mb = mb[(mb['Age'] > age_select[0]) & (mb['Age'] <= age_select[1])]
    fig = px.scatter(filtered_mb, x = 'spAge', y = 'spComfort', color = 'Sex')
    return fig


if __name__ == '__main__':
    app1.run(debug = True)

In [16]:
app2 = Dash()
app2.layout = html.Div([
    html.H1("David's Awesome App"),
    html.H2("Some subheading"),
    dcc.Graph(id = 'spComfort-spAge_figure'),
    dcc.RangeSlider(20,
               90,
               step = 10,
               value = [20, 90],
               id = 'Age_slider')
])

@callback(
    Output('spComfort-spAge_figure', 'figure'),
    Input('Age_slider', 'value')
)
def update_fig(age_select):
    filtered_mb = mb[(mb['Age'] > age_select[0]) & (mb['Age'] <= age_select[1])]
    men_mb = filtered_mb[filtered_mb['Sex'] == 1]
    women_mb = filtered_mb[filtered_mb['Sex'] == 2]
    
    trace_men = go.Scatter(x = men_mb['spAge'], y = men_mb['spComfort'],
                           mode = 'markers', name = 'Men')
    trace_women = go.Scatter(x = women_mb['spAge'], y = women_mb['spComfort'],
                             mode = 'markers', name = 'Women')
    fig = go.Figure(data = [trace_men, trace_women])
    # fig = px.scatter(filtered_mb, x = 'spAge', y = 'spComfort', color = 'Sex')
    return fig


if __name__ == '__main__':
    app2.run(debug = True)