In [1]:
import plotly as pl
import plotly.express as px
import pandas as pd

In [2]:
fdo = pd.read_csv('daily_food_delivery_orders.csv')
fdo.head()

,order_id,order_date,customer_age,restaurant_type,order_value,delivery_distance_km,delivery_time_minutes,payment_method,delivery_partner_rating,order_status
0,1,2024-11-05,62,Indian,497.51,11.07,79,UPI,3.9,Cancelled
1,2,2024-08-20,35,Bakery,232.32,5.83,69,Wallet,2.7,Cancelled
2,3,2024-02-28,34,Italian,540.82,3.61,70,Wallet,3.4,Cancelled
3,4,2024-05-26,65,Cafe,1197.99,3.66,18,Card,4.6,Cancelled
4,5,2024-09-21,40,Indian,947.03,12.08,57,UPI,4.9,Delayed

In [12]:
status_counts = fdo['restaurant_type'].value_counts().reset_index()
status_counts.columns = ['restaurant_type', 'frequency']
fig1 = px.bar(status_counts,
              x = 'restaurant_type',
              y = 'frequency',
              title = "frequency of Restaurant Type",
              labels = {'restaurant_type': "Restaurant Type", 'frequency': 'Count'},
              text = 'frequency',
              color = 'restaurant_type',
              color_discrete_sequence = ['tan', '#D3885D', 'red', 'yellow', 'green', 'orange']
              )
fig1.show()

In [13]:
fdo_20 = fdo.head(20)
fdo_20

,order_id,order_date,customer_age,restaurant_type,order_value,delivery_distance_km,delivery_time_minutes,payment_method,delivery_partner_rating,order_status
0,1,2024-11-05,62,Indian,497.51,11.07,79,UPI,3.9,Cancelled
1,2,2024-08-20,35,Bakery,232.32,5.83,69,Wallet,2.7,Cancelled
2,3,2024-02-28,34,Italian,540.82,3.61,70,Wallet,3.4,Cancelled
3,4,2024-05-26,65,Cafe,1197.99,3.66,18,Card,4.6,Cancelled
4,5,2024-09-21,40,Indian,947.03,12.08,57,UPI,4.9,Delayed
5,6,2024-03-16,51,Italian,835.75,3.56,85,UPI,3.8,Delayed
6,7,2024-11-20,52,Cafe,771.83,14.37,80,Card,3.7,Delivered
7,8,2024-11-24,52,Chinese,926.20,12.81,19,UPI,4.4,Delayed
8,9,2024-07-23,38,Bakery,548.11,13.54,42,Cash,4.1,Delayed
9,10,2024-07-01,24,Fast Food,177.18,8.15,29,Cash,2.9,Delivered
10,11,2024-09-16,27,Cafe,806.68,5.43,53,Cash,3.1,Cancelled
11,12,2024-08-27,61,Bakery,1193.33,9.68,26,UPI,3.5,Delivered
12,13,2024-01-09,31,Chinese,758.14,1.28,57,Cash,2.9,Delayed
13,14,2024-09-02,47,Cafe,937.07,13.41,88,Wallet,3.8,Cancelled
14,15,2024-08-21,62,Chinese,810.18,12.36,87,Cash,5.0,Delayed
15,16,2024-07-24,38,Bakery,773.12,9.07,50,Wallet,2.8,Cancelled
16,17,2024-04-09,54,Cafe,816.14,10.95,86,UPI,4.8,Delayed
17,18,2024-04-20,43,Cafe,640.60,4.49,50,Cash,4.1,Delayed
18,19,2024-03-01,54,Indian,193.87,4.40,63,UPI,2.8,Delivered
19,20,2024-08-23,23,Chinese,183.09,14.11,52,Cash,2.9,Cancelled

In [15]:
fig2 = px.line(fdo_20,
               x = 'order_date',
               y = 'order_value',
               markers = True)

fig2.show()

In [19]:
fdo_20.loc[:,'datetime'] = pd.to_datetime(fdo_20['order_date'])
fdo_20.sort_values('datetime', inplace = True)

C:\Users\dsilva2\AppData\Local\Temp\ipykernel_25796\315912817.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [26]:
fig3 = px.line(fdo_20,
               x = 'datetime',
               y = 'order_value',
               markers = True,
               labels = {'datetime': 'Order Date',
                         'order_value': 'Order Value'})

fig3.update_traces(marker = {'color': 'green',
                             'size': 10,
                             'symbol': 'square'},
                    line = {'width': 3, 'color': 'red'})

fig3.show()

In [29]:
fig4 = px.scatter(fdo,
                  x = 'delivery_distance_km',
                  y = 'delivery_time_minutes',
                  color = 'delivery_partner_rating',
                  symbol = 'order_status')

fig4.show()

In [30]:
fdo_samp = fdo.sample(n = 50)
fdo_samp.head()

,order_id,order_date,customer_age,restaurant_type,order_value,delivery_distance_km,delivery_time_minutes,payment_method,delivery_partner_rating,order_status
2535,2536,2024-06-29,31,Chinese,930.50,7.21,19,Card,4.1,Delayed
1987,1988,2024-05-06,51,Chinese,438.94,13.21,90,UPI,4.2,Delivered
97,98,2024-01-10,48,Italian,261.92,6.57,46,UPI,3.1,Cancelled
1313,1314,2024-07-16,43,Chinese,737.65,8.14,43,Card,3.4,Delayed
965,966,2024-05-19,55,Indian,686.57,8.04,64,UPI,3.1,Delivered

In [41]:
fig5 = px.scatter(fdo_samp,
                  x = 'delivery_distance_km',
                  y = 'delivery_time_minutes',
                  color = 'delivery_partner_rating',
                  symbol = 'order_status')

fig5.update_traces(marker = {'size': 20, 'opacity': 0.5,
                             'line': {'width': 2, 'color': 'black'}})

fig5.update_layout(legend = {'yanchor': 'top', 'y': 0.98, 'xanchor': 'left', 'x': 1.23})

fig5.show()